using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoftUniDBFirst
{
    class Program
    {
        static void Main(string[] args)
        {
            var employee = new Employee
            {
                FirstName = "Petar",
                LastName = "Ivanov",
                JobTitle = "Design Engineer",
                DepartmentID = 2,
                HireDate = new DateTime(2014, 1, 1),
                Salary = 35000
            };

            //Write a testing class which:
            //1.	Inserts an employee

            //DataAccessObject.Add(employee);

            //2.	Prints his/her primary key generated by the DB
            //Console.WriteLine(employee.EmployeeID);

            //3.	Changes the employee first name and saves it to the database

            using (var context = new SoftUniEntities())
            {
                var addresses = context.Addresses
                    .OrderByDescending(a => a.Employees.Count())
                    .ThenBy(a => a.Town.Name)
                    .Select(a => new
                    {
                        Address = a.AddressText,
                        Town = a.Town.Name,
                        EmployeeCount = a.Employees.Count
                    })
                    .Take(10);

                foreach (var address in addresses)
                {
                    Console.WriteLine("{0}, {1} - {2} employees",
                        address.Address, address.Town, address.EmployeeCount);
                }
            }

            using (var context = new SoftUniEntities())
            {
                var emp = context.Employees
                    .Where(e => e.EmployeeID == 147)
                    .Select(e => new
                    {
                        e.FirstName,
                        e.LastName,
                        e.JobTitle,
                        projects =
                            e.Projects
                            .OrderBy(p => p.Name)
                            .Select(p => p.Name)
                            .ToList()
                    })
                    .First();

               Console.WriteLine("{0} {1} - {2} - projects - {3}", emp.FirstName, emp.LastName, emp.JobTitle, string.Join(", ", emp.projects));
                
            }
        }
    }
}
