using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SoftUniDBFirst
{
    class Program
    {
        static void Main(string[] args)
        {
            var employee = new Employee
            {
                FirstName = "Petar",
                LastName = "Ivanov",
                JobTitle = "Design Engineer",
                DepartmentID = 2,
                HireDate = new DateTime(2014, 1, 1),
                Salary = 35000
            };

            //Write a testing class which:
            //1.	Inserts an employee

            DataAccessObject.Add(employee);

            //2.	Prints his/her primary key generated by the DB
            Console.WriteLine(employee.EmployeeID);

            //3.	Changes the employee first name and saves it to the database


        }
    }
}
